### ISSUE TITLE
Develop the html documentation

### ISSUE THREAD

**Issue by Annanardo** [Annanardo/Art#13]

**Comment by melissamattiolii** [comment]
Done in:
https://github.com/Annanardo/Art/blob/main/biography_function.html 
https://github.com/Annanardo/Art/blob/main/inserter.html 
https://github.com/Annanardo/Art/blob/main/checking.html 
https://github.com/Annanardo/Art/blob/main/inserter.html 
https://github.com/Annanardo/Art/blob/main/similarities.html
https://github.com/Annanardo/Art/blob/main/test.html

**Comment by melissamattiolii** [comment]
done

**Comment by vittorialazzer** [comment]
Fixed in 9b4e2e0787506bfe20c584b367843bda9f834471
