### ISSUE TITLE
Adjust the README.md file

### ISSUE THREAD

**Issue by Annanardo** [Annanardo/Art#9]

**Comment by melissamattiolii** [comment]
added similarities function and fixed some errors in https://github.com/Annanardo/Art/commit/082d71d415f3740921ecc5ef51e64a3dad7f5884

**Comment by melissamattiolii** [comment]
fixed some errors and modified README in https://github.com/Annanardo/Art/commit/6cd2859b3f9673d5749b6772863374fe30402aeb

**Comment by Annanardo** [comment]
Finished in https://github.com/Annanardo/Art/commit/322550e485e5a0df6425576701a85e0af9992af8
